// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: messages.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mention_MentionType int32

const (
	Mention_Unspecified Mention_MentionType = 0
	Mention_At          Mention_MentionType = 1
	Mention_Hash        Mention_MentionType = 2
	Mention_Dollar      Mention_MentionType = 3
	Mention_Tilda       Mention_MentionType = 4
)

// Enum value maps for Mention_MentionType.
var (
	Mention_MentionType_name = map[int32]string{
		0: "Unspecified",
		1: "At",
		2: "Hash",
		3: "Dollar",
		4: "Tilda",
	}
	Mention_MentionType_value = map[string]int32{
		"Unspecified": 0,
		"At":          1,
		"Hash":        2,
		"Dollar":      3,
		"Tilda":       4,
	}
)

func (x Mention_MentionType) Enum() *Mention_MentionType {
	p := new(Mention_MentionType)
	*p = x
	return p
}

func (x Mention_MentionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mention_MentionType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (Mention_MentionType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x Mention_MentionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mention_MentionType.Descriptor instead.
func (Mention_MentionType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ThreadId      *uint64                `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3,oneof" json:"thread_id,omitempty"`
	AccountId     *uint64                `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Mentions      []*Mention             `protobuf:"bytes,5,rep,name=mentions,proto3" json:"mentions,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetThreadId() uint64 {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return 0
}

func (x *Message) GetAccountId() uint64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetMentions() []*Mention {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Mention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Mention_MentionType    `protobuf:"varint,2,opt,name=type,proto3,enum=api.Mention_MentionType" json:"type,omitempty"`
	Start         uint32                 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mention) Reset() {
	*x = Mention{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mention) ProtoMessage() {}

func (x *Mention) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mention.ProtoReflect.Descriptor instead.
func (*Mention) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Mention) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mention) GetType() Mention_MentionType {
	if x != nil {
		return x.Type
	}
	return Mention_Unspecified
}

func (x *Mention) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Mention) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Create struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create) Reset() {
	*x = Create{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create) ProtoMessage() {}

func (x *Create) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create.ProtoReflect.Descriptor instead.
func (*Create) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

type Get struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get) Reset() {
	*x = Get{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

type Create_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      *uint64                `protobuf:"varint,2,opt,name=thread_id,json=threadId,proto3,oneof" json:"thread_id,omitempty"`
	AccountId     *uint64                `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3,oneof" json:"account_id,omitempty"`
	Mentions      map[string]uint64      `protobuf:"bytes,4,rep,name=mentions,proto3" json:"mentions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create_Request) Reset() {
	*x = Create_Request{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Request) ProtoMessage() {}

func (x *Create_Request) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Request.ProtoReflect.Descriptor instead.
func (*Create_Request) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Create_Request) GetThreadId() uint64 {
	if x != nil && x.ThreadId != nil {
		return *x.ThreadId
	}
	return 0
}

func (x *Create_Request) GetAccountId() uint64 {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return 0
}

func (x *Create_Request) GetMentions() map[string]uint64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Create_Request) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Create_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Create_Response) Reset() {
	*x = Create_Response{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Create_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Create_Response) ProtoMessage() {}

func (x *Create_Response) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Create_Response.ProtoReflect.Descriptor instead.
func (*Create_Response) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Create_Response) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type Get_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []uint64               `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Request) Reset() {
	*x = Get_Request{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Request) ProtoMessage() {}

func (x *Get_Request) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Request.ProtoReflect.Descriptor instead.
func (*Get_Request) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Get_Request) GetId() []uint64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type Get_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Response) Reset() {
	*x = Get_Response{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Response) ProtoMessage() {}

func (x *Get_Response) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Response.ProtoReflect.Descriptor instead.
func (*Get_Response) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Get_Response) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Delete_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete_Request) Reset() {
	*x = Delete_Request{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Request) ProtoMessage() {}

func (x *Delete_Request) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Request.ProtoReflect.Descriptor instead.
func (*Delete_Request) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Delete_Request) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Delete_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete_Response) Reset() {
	*x = Delete_Response{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete_Response) ProtoMessage() {}

func (x *Delete_Response) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete_Response.ProtoReflect.Descriptor instead.
func (*Delete_Response) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4, 1}
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xfb\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12 \n" +
	"\tthread_id\x18\x02 \x01(\x04H\x00R\bthreadId\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x04H\x01R\taccountId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\bmentions\x18\x05 \x03(\v2\f.api.MentionR\bmentions\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontentB\f\n" +
	"\n" +
	"_thread_idB\r\n" +
	"\v_account_id\"\xb8\x01\n" +
	"\aMention\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.api.Mention.MentionTypeR\x04type\x12\x14\n" +
	"\x05start\x18\x03 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\rR\x03end\"G\n" +
	"\vMentionType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\x06\n" +
	"\x02At\x10\x01\x12\b\n" +
	"\x04Hash\x10\x02\x12\n" +
	"\n" +
	"\x06Dollar\x10\x03\x12\t\n" +
	"\x05Tilda\x10\x04\"\xc1\x02\n" +
	"\x06Create\x1a\x82\x02\n" +
	"\aRequest\x12 \n" +
	"\tthread_id\x18\x02 \x01(\x04H\x00R\bthreadId\x88\x01\x01\x12\"\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x04H\x01R\taccountId\x88\x01\x01\x12=\n" +
	"\bmentions\x18\x04 \x03(\v2!.api.Create.Request.MentionsEntryR\bmentions\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x1a;\n" +
	"\rMentionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\f\n" +
	"\n" +
	"_thread_idB\r\n" +
	"\v_account_id\x1a2\n" +
	"\bResponse\x12&\n" +
	"\amessage\x18\x01 \x01(\v2\f.api.MessageR\amessage\"V\n" +
	"\x03Get\x1a\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x04R\x02id\x1a4\n" +
	"\bResponse\x12(\n" +
	"\bmessages\x18\x01 \x03(\v2\f.api.MessageR\bmessages\"1\n" +
	"\x06Delete\x1a\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\x1a\n" +
	"\n" +
	"\bResponse2\xee\x01\n" +
	"\vMessagesAPI\x12M\n" +
	"\x06Create\x12\x13.api.Create.Request\x1a\x14.api.Create.Response\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/messages\x12A\n" +
	"\x03Get\x12\x10.api.Get.Request\x1a\x11.api.Get.Response\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/messages\x12M\n" +
	"\x06Delete\x12\x13.api.Delete.Request\x1a\x14.api.Delete.Response\"\x18\x82\xd3\xe4\x93\x02\x12:\x01**\r/api/messagesB&Z$github.com/skamenetskiy/messages/apib\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messages_proto_goTypes = []any{
	(Mention_MentionType)(0),      // 0: api.Mention.MentionType
	(*Message)(nil),               // 1: api.Message
	(*Mention)(nil),               // 2: api.Mention
	(*Create)(nil),                // 3: api.Create
	(*Get)(nil),                   // 4: api.Get
	(*Delete)(nil),                // 5: api.Delete
	(*Create_Request)(nil),        // 6: api.Create.Request
	(*Create_Response)(nil),       // 7: api.Create.Response
	nil,                           // 8: api.Create.Request.MentionsEntry
	(*Get_Request)(nil),           // 9: api.Get.Request
	(*Get_Response)(nil),          // 10: api.Get.Response
	(*Delete_Request)(nil),        // 11: api.Delete.Request
	(*Delete_Response)(nil),       // 12: api.Delete.Response
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_messages_proto_depIdxs = []int32{
	13, // 0: api.Message.created_at:type_name -> google.protobuf.Timestamp
	2,  // 1: api.Message.mentions:type_name -> api.Mention
	0,  // 2: api.Mention.type:type_name -> api.Mention.MentionType
	8,  // 3: api.Create.Request.mentions:type_name -> api.Create.Request.MentionsEntry
	1,  // 4: api.Create.Response.message:type_name -> api.Message
	1,  // 5: api.Get.Response.messages:type_name -> api.Message
	6,  // 6: api.MessagesAPI.Create:input_type -> api.Create.Request
	9,  // 7: api.MessagesAPI.Get:input_type -> api.Get.Request
	11, // 8: api.MessagesAPI.Delete:input_type -> api.Delete.Request
	7,  // 9: api.MessagesAPI.Create:output_type -> api.Create.Response
	10, // 10: api.MessagesAPI.Get:output_type -> api.Get.Response
	12, // 11: api.MessagesAPI.Delete:output_type -> api.Delete.Response
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_messages_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
